#!/bin/sh

export PATH=/bin

mount -t proc proc /proc
dmesg -n 1
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /var/run
mount -t devtmpfs devtmpfs /dev
mount -t vfat /dev/mmcblk0p1 /boot

exec getty 115200 /dev/tty0 linux
