#!/bin/sh

export PATH=/bin

# Stay PID 1: toybox poweroff/reboot/halt send SIGUSR2/TERM/USR1 to init.
# exec'ing getty would make getty PID 1 and those signals do nothing.
trap 'sync; poweroff -f' USR2
trap 'sync; reboot -f' TERM
trap 'sync; halt -f' USR1

mount -t proc proc /proc
dmesg -n 1
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /run
mount -t tmpfs tmpfs /var/run
mount -t devtmpfs devtmpfs /dev
mount -t vfat /dev/mmcblk0p1 /boot

modprobe hid_apple
modprobe realtek
modprobe rtl8150
modprobe r8152
modprobe cfg80211
modprobe mac80211
modprobe rfkill
modprobe rtl8xxxu

clear
while true; do
	getty 115200 tty0 linux
done
